### PR TITLE
Added option to show macro replacements

### PR DESCRIPTION
**Pull request by Dayvison**
Using the `-m`

* Code
```pawn
#define A B
#define B C
#define C D

A
```

* Output
```
MACRO(A->B) INPUT(A) OUTPUT(B)
MACRO(B->C) INPUT(B) OUTPUT(C)
MACRO(C->D) INPUT(C) OUTPUT(D)
```
  
ps: I don't known C, if someone know how to improve...

### CODE REVIEW

**Comment by Y-Less** [comment]
How compatible is this with @oscar-broman's changes from before to output macros from the compiler?

**Comment by YashasSamaga** [comment]
```
[00:00:40] Test project C:/projects/pawn
[00:00:40]     Start 1: gh_217
[00:00:40] 1/3 Test #1: gh_217 ...........................   Passed    0.05 sec
[00:00:40]     Start 2: macro_output
[00:00:40] 2/3 Test #2: macro_output .....................***Failed  Required regular expression not found.Regex=[.* MACRO(A->B) INPUT(A) OUTPUT(B).* MACRO(B->C) INPUT(B) OUTPUT(C).* MACRO(C->D) INPUT(C) OUTPUT(D)
[00:00:40] ]  0.00 sec
[00:00:40]     Start 3: md_array_crash_gh_220
[00:00:40] 3/3 Test #3: md_array_crash_gh_220 ............   Passed    0.59 sec
[00:00:40] 
[00:00:40] 67% tests passed, 1 tests failed out of 3
[00:00:40] 
[00:00:40] Total Test time (real) =   0.64 sec
[00:00:40] 
[00:00:40] The following tests FAILED:
[00:00:40] 	  2 - macro_output (Failed)
[00:00:40] Errors while running CTest
```

**Comment by Dayvison** [comment]
@YashasSamaga my mistake in the regex.
@Y-Less if you talking about the patch made for ppg, both use `-m`, but my is for human read i think his is more for machine

**Comment by YashasSamaga** [comment]
@Dayvison Your fork of this repository is quite old. You need to use an updated fork and patch the compiler again or modify `sc1.c` (not recommended) to match the file in the master branch to resolve the conflict.

**Comment by YashasSamaga** [comment]
@Dayvison Can you resolve the merge conflicts?

**Comment by Y-Less** [comment]
> if you talking about the patch made for ppg, both use -m, but my is for human read i think his is more for machine

I don't think it's a good idea to have two versions of the same thing with the same flag be subtly different.  Also, in general, I'd say that a machine-readable version was more useful - a human-readable version can be quickly parsed from that while also providing other tooling output, but the reverse is not true.

**Comment by Dayvison** [comment]
I will open another PR because github merge is sucks, and make some changes.

- Change flag to `-M`(upper)
- Alter output to only macro name `MACRO(in(%0)->out(%0))` to `MACRO(in)`
- Correct the tests

**Comment by Y-Less** [comment]
> [14:21] Dayvison: @Y_Less i don't understand what you say here: 

> > I'd say that a machine-readable version was more useful - a human-readable version can be quickly parsed from that while also providing other tooling output, but the reverse is not true.

> [14:22] Dayvison: My english is poor, and in my language many things come out of context
> [14:22] Y_Less: I that if the output is machine readable, it is very easy to write a tool to make that machine-readable output human-readable.
> [14:22] Y_Less: However, if the output is human-readable, using that in a tool is hard.
> [14:23] Y_Less: machine -> human is easy
> [14:23] Y_Less: human -> machine is hard
> [14:23] Y_Less: So the better output is machine readable, because making that human readable as well is easy.
> [14:25] ETInat0r: I think anyone can define automata, which can be easily and efficiently translated into ASM
> [14:35] Dayvison: But a machine-readable make you dependent of a external program
> [14:36] Yashas: @Dayvison You can rebase your fork to resolve the merge conflicts without causing unwanted merge commits.
> [14:38] Yashas: You might also want to rebase your fork as it is way behind upstream repo.
> [14:39] Dayvison: I'm seeing it now https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa
> [14:40] Y_Less: @Dayvison but a human readable format makes other tools much much harder.
> [14:40] Y_Less: So you are simplifying one tool at the expense of all other.
> [14:41] Yashas: @Dayvison  You can stash your commits and move the HEAD backwards  to a state where you can rebase using reset (you can also use reflog if you had a local repo). Afte rebasing you can pop the stash and resolve conflicts. You'll now have your merge commits resolved as well as rebased without extra commits.(edited)
> [14:45] Dayvison: @Yashas reset HEAD^ but this is only local i guess, but don't worry i make another branch from pawn-lang version
> [14:46] Dayvison: Y_Less i will change the flag to  -Mthat way will make compatible with ppg
> [14:47] Y_Less: @Dayvison That's a worse idea.  Then there are two flags to do almost the same thing in different ways.
> [14:49] Dayvison: I get what you saying
> [14:49] Dayvison: i can keep this for myself with a git patch
> [14:51] Y_Less: Macro steps output is very useful.  I'm not sure why you're opposed to outputting it in a way that other people can use.
> [14:53] Dayvison: What I understood is the macro output is not good in that way, and is better in machine-readable. What is your idea then?
> [14:54] Y_Less: Yes, that was my point.
> [14:54] Y_Less: human readable output is bad
> [14:54] Y_Less: machine readable output is good
> [14:55] Y_Less: If it is human readable, using it in a tool is tricky, so you limit how useful it it.
> [14:55] Y_Less: If it is machine readable, using it in a tool is easy, so you can do anything with it, including making it human readable.
> [15:04] Dayvison: So you think is better no add the human-readable in the compiler?
> [15:05] Y_Less: Yes
> [15:06] Y_Less: Just add machine-readable in the compiler.  Then anyone can use it in any way.
> [15:07] Dayvison: But i'm not the author of machine-readable so i cant add that
> [15:19] Y_Less: Can you not tweak your current code to just output in a slightly different format?
> [15:25] Dayvison: to make compatible with ppg, needs other things, maybe just make a git patch in oscar-broman repo and push to pawn-lang repo(edited)

**Pull request closed without merging**
