### PR TITLE
Write `.lst` after the second pass.

### LINKED ISSUE #116: -l bug
Default ALS method:
```Pawn
native printf(const format[], {Float,_}:...);
forward OnGameModeInit();

main() {}

// ---------------------------------------------------------------------
public OnGameModeInit()
{
	printf("OnGameModeInit 1");
	#if defined Prefix_OnGameModeInit
		return Prefix_OnGameModeInit();
	#else
		return 1;
	#endif
}
#if defined _ALS_OnGameModeInit
	#undef OnGameModeInit
#else
	#define _ALS_OnGameModeInit
#endif

#define OnGameModeInit Prefix_OnGameModeInit
#if defined Prefix_OnGameModeInit
	forward Prefix_OnGameModeInit();
#endif

// ---------------------------------------------------------------------
public OnGameModeInit()
{
	printf("OnGameModeInit 2");
	#if defined Prefix2_OnGameModeInit
		return Prefix2_OnGameModeInit();
	#else
		return 1;
	#endif
}
#if defined _ALS_OnGameModeInit
	#undef OnGameModeInit
#else
	#define _ALS_OnGameModeInit
#endif

#define OnGameModeInit Prefix2_OnGameModeInit
#if defined Prefix2_OnGameModeInit
	forward Prefix2_OnGameModeInit();
#endif

// ---------------------------------------------------------------------
public OnGameModeInit()
{
	printf("OnGameModeInit");
	return 1;
}
```
Results:
```
OnGameModeInit 1
OnGameModeInit 2
OnGameModeInit
```
It's ok, but if I compile it with -l param, I got this:
```Pawn
#pragma ctrlchar 0x5c
#pragma pack false
#pragma semicolon true
#pragma tabsize 8
#file "sources\default.pwn"
#line 1

native printf(const format[], {Float,_}:...);

main() {}

forward OnGameModeInit();

public OnGameModeInit()
{
	printf("OnGameModeInit 1");
#line 14
		return 1;
#line 16
}
#line 22

#line 27






public Prefix_OnGameModeInit()
{
	printf("OnGameModeInit 2");
#line 39
		return 1;
#line 41
}
#line 47

#line 52


public Prefix2_OnGameModeInit()
{
	printf("OnGameModeInit");
	return 1;
}
```
And this is wrong.

### PR DESCRIPTION
**Pull request by Y-Less**
**What this PR does / why we need it**:

This moves the `-l` code output to after the second pass, so that the generated code is the most accurate it can be.
-

**Which issue(s) this PR fixes**:

Fixes #116

**What kind of pull this is**:

* [x] A Bug Fix
* [ ] A New Feature
* [ ] Some repository meta (documentation, etc)
* [ ] Other

**Additional Documentation**:

### CODE REVIEW

**Comment by Southclaws** [comment]
I might revive my parser project because of this!

**Comment by AGraber** [comment]
I think there should be a way to still print the first pass, through another flag of course.

**Comment by Southclaws** [comment]
Yes that would be useful for investigating exactly what the difference is with complex macros.

**Comment by Y-Less** [comment]
The only difference this makes to macros is code like this:

```pawn
#if defined Hooked_OnPlayerConnect
    Hooked_OnPlayerConnect(playerid);
#endif
```

All other macros, unless you are doing very odd things with future definitions, will be the same.  It doesn't replace at a later stage in macro replacement, those have always been atomic.

**Comment by Southclaws** [comment]
Code looks fine to my (untrained) eyes, since I intend to work on a parser soon I wanted to get this in for the next version. I'll hopefully get around to testing this at the weekend.

**Pull request merged**
