### PR TITLE
allow {...}: any tag for arguments

### LINKED ISSUE #264: "Any" tag `{...}:`
Would be useful for functions like `CallLocalFunction` where the varargs can be anything:

```pawn
native CallLocalFunction(const func[], const types[], {...}:...);
```

Don't know if `{...}:` is the best syntax, though it has the advantage of being similar to existing syntax for varargs, "rest" in array initialisation, and groups of tags; plus the advantage of not being a symbol like `Any;` which could be in use elsewhere.  The downsides being it is a little verbose and `{...}:...` is confusing.

I gave an example with varargs, but that isn't the only version.  Also `{...}:a, b = tagof (a)` should return the original tag, not a special representation of `{...}`.

### PR DESCRIPTION
**Pull request by YashasSamaga**
**What this PR does / why we need it**:
Allows the use of `{...}:` as tags for an argument. 

**Which issue(s) this PR fixes**:

Fixes #264 

**Quick tests:**

```
f1({...}:arg) {
	#pragma unused arg
}

g1(arg) {
	#pragma unused arg
}

g1_1({Float}:arg) {
	#pragma unused arg
}

f2({...}:arg = Tag:5) {
	#pragma unused arg
}

g2(arg = Tag:5) { // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	#pragma unused arg
}

g2_1({Float}:arg = Tag:5) { // warning 213: tag mismatch: expected tag "Float", but found "Tag"
	#pragma unused arg
}

f3({...}:arg = tag:5) {
	#pragma unused arg
}

g3(arg = tag:5) {
	#pragma unused arg
}

g3_1({Float, tag}:arg = tag:5) { // warning 213: tag mismatch: expected tag "Float", but found "Tag"
	#pragma unused arg
}

f4(const {...}:arg[] = {Tag:1}){
	#pragma unused arg
}

g4(const arg[] = {Tag:1}) { // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	#pragma unused arg
}

f5(const {...}:arg[][] = {{Tag:1}}) {
	#pragma unused arg
}

g5(const arg[][] = {{Tag:1}}) { // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	#pragma unused arg
}

f6({...}:&arg = Tag:5) {
	#pragma unused arg
}

g6(&arg = Tag:5) { // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	#pragma unused arg
}

f7({...}:...) {

}

g7(...) {

}


main() {
	f1(Tag:0);
	f1(0);
	f1(tag:0);
	g1(Tag:0); // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	g1(0);
	g1(tag:0);
	g1_1(Tag:0);// warning 213: tag mismatch: expected tag "Float", but found "Tag"
	g1_1(Float:0);
	g1_1(0);// warning 213: tag mismatch: expected tag "Float", but found none ("_")
	g1_1(tag:0); // warning 213: tag mismatch: expected tag "Float", but found "tag"
	
	f2();
	f2(Tag:0);
	g2();
	g2(Tag:0); // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	g2_1();
	g2_1(Tag:0); // warning 213: tag mismatch: expected tag "Float", but found "Tag"
	
	f3();
	f3(Tag:0);
	g3();
	g3(Tag:0); // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	g3_1();
	g3_1(Tag:0); // warning 213: tag mismatch: expected tags "Float", or "tag"; but found "Tag"

	f4();
	f4({Tag:0});
	g4();
	g4({Tag:0});

	new Tag:tmp[][] = {{0}}; // warning 213: tag mismatch: expected tag "Tag", but found none ("_")
	f5();
	f5(tmp);
	g5();
	g5(tmp); // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	
	f6();
	f6(tmp[0][0]);
	g6();
	g6(tmp[0][0]); // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
	
	f7(Tag:5);
	g7(Tag:5); // warning 213: tag mismatch: expected tag none ("_"), but found "Tag"
}

new arr1[5];
new arr2[] = {0};
new arr3[] = Tag:{ 0 };

#pragma unused arr1
#pragma unused arr2
#pragma unused arr3

f15({..., Float}:arg) { // error 001: expected token: "}", but found ","

}

f16({Float, ...}:arg) { // error 001: expected token: "-tagname-", but found "..."

}

#pragma unused f15
#pragma unused f16

enum ITEM {
	Float:item
};
new arr4[ITEM] = {Tag:0};
#pragma unused arr4
```

### CODE REVIEW

**Comment by Y-Less** [comment]
I was going to say this needs tests, then I saw you already wrote that.  So why make a pull request in the first place?

**Comment by YashasSamaga** [comment]
The AppVeyor build becomes available for people to test and people would attempt to look at the code.

I prefer adding the tests at the end since there could be changes to the PR.

**Comment by Y-Less** [comment]
How is this one looking now? I see there are merge conflicts, but there are also now tests, while still stating not to merge in the first post due to a lack of them.

**Comment by YashasSamaga** [comment]
The commits in the PR add a new parameter to a bunch of functions for the sake of this feature. The code needs to be reviewed I think.

**Comment by YashasSamaga** [comment]
Updated the tests and resolved conflicts.

The PR is ready if people are ok with the code.

**Comment by Southclaws** [comment]
LGTM!

**Comment by YashasSamaga** [comment]
```
f({...}:args) {
	new x = tagof(args);
}
```

requires an error but none of the existing error appears to describe the situation well.

**Comment by YashasSamaga** [comment]
`indeterminate tag in \"tagof\" expression (symbol \"%s\")\n`

This will be a warning (like the similar `sizeof` equivalent) and the expression will default to the tag of the untagged cell.

Will push a commit in two days if there aren't any issues.

**Pull request closed without merging**
