### PR TITLE
Operator '__fallthrough'

### PR DESCRIPTION
**Pull request by Daniel-Cortez**
**What this PR does / why we need it**:

This PR implements operator `__fallthrough`, which, as the name suggests, can be used to make "fall-through" switch cases.
Example:
```Pawn
SendClientMessage(playerid, -1, "Available admin commands:");
switch (player_info[playerid][pAdminLvl])
{
    case 3:
    {
        SendClientMessage(playerid, -1, "Level 3: /makeadmin [playerid] [level]");
        __fallthrough; // Show commands for the previous admin levels as well
    }
    case 2:
    {
        SendClientMessage(playerid, -1, "Level 2: /tphere [playerid], /abroadcast [text]");
        __fallthrough;
    }
    case 1:
    {
        SendClientMessage(playerid, -1, "Level 1: /kick [playerid] [reason], /ban [playerid] [reason]");
        __fallthrough; // Silently ignored, as this is the last case
    }
}
```

**Which issue(s) this PR fixes**:

Fixes #

**What kind of pull this is**:

* [ ] A Bug Fix
* [x] A New Feature
* [ ] Some repository meta (documentation, etc)
* [ ] Other

**Additional Documentation**:

### CODE REVIEW

**Comment by Y-Less** [comment]
I'm not convinced this is needed,  Pawn cases were explicitly designed to counter the common issues with C cases from fallthrough.  While explicit is better than implicit, you can already do it with `goto`.

**Comment by Daniel-Cortez** [comment]
> Pawn cases were explicitly designed to counter the common issues with C cases from fallthrough.

As far as I can understand, `__fallthrough` shouldn't cause any of those issues since its used in an explicit way.

> While explicit is better than implicit, you can already do it with goto.

`goto` requires the user to define a label in the next case and generates extra code (one `jump` and a pair of `lctrl`/`sctrl` to readjust the stack pointer), both of which, IMHO, are excessive for a simple fallthrough case. Operator `__fallthrough` doesn't do any of that.

**Comment by YashasSamaga** [comment]
I think we should have a generic system. In C++, this would be done using `[[fallthrough]]` where `[[]]` is called attribute specifier sequence.

There was a discussion earlier about such a thing #267.

**Comment by Y-Less** [comment]
You're talking about adding a whole new keyword (which should only be done extremely sparingly) to save two instructions in a rare corner-case.  That's why I don't think it is worth it.

**Comment by Y-Less** [comment]
The real response should be improving the behaviour of `goto` to not reset the stack when it doesn't need to.  Or just adjust it by however much is required to change between two variable scopes.  This solution does also have stack adjusting ops, just not in any of the given tests, because none of those have case-local variables.

**Comment by Daniel-Cortez** [comment]
> You're talking about adding a whole new keyword (which should only be done extremely sparingly) to save two instructions in a rare corner-case. That's why I don't think it is worth it.

Then would it be OK to reimplement this feature as `#pragma fallthrough`? If I understand it correctly, `#pragma` **is** pretty much designed for rare corner cases.

>The real response should be improving the behaviour of goto to not reset the stack when it doesn't need to. Or just adjust it by however much is required to change between two variable scopes.

I think this would require implementing an ability to reparse functions, because the compiler can't know in advance in which scope the label is if it's used in `goto` before the point of its definition. This would also open a way to fix other related problems (e.g. destructors for local variables not being called when branching out of their scope with `goto`).

**Pull request closed without merging**
