### PR TITLE
elaborated on contribution guidelines

### PR DESCRIPTION
**Pull request by Southclaws**
This change just improves the wording around contribution in the readme, contributing and PR template to ensure contributors discuss proposed changes before actually writing any code to save time during code review.

### CODE REVIEW

**Comment by Y-Less** [comment]
Was this change discussed in an issue before submitting?

**Comment by Southclaws** [comment]
Okay you got me there...

**Comment by Zeex** [comment]
Is building from source code always associated with the desire to contribute? I mean maybe someone reading the readme just wants to know how to compile the code, so maybe there should still be a link to the build steps somewhere in the file. Anyway, that's just my opinion.

**Comment by Y-Less** [comment]
The link is still there, but maybe it should be clearer by keeping its header.

**Comment by Southclaws** [comment]
Fair point, I'll re-word it a bit.

**Comment by Y-Less** [comment]
> 
> 
> Fair point, I'll re-word it a bit.

@Southclaws

**Pull request merged**
